version: '3.2'
services:
  db:
    image: postgres

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports: 
      - 4000
    depends_on:
      - db
    links:
      - db
    command:
      - ./run.sh
