version: '3.2'
services:
  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports: 
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
    command:
      - ./run.sh
    env_file:
      - .env
